- name: "Disable repositories"
  command: subscription-manager repos --disable='*'

- name: "Enable repositories"
  command: subscription-manager repos --enable={{ item }}
  with_items: "{{ repos }}"

